export const AuthConstants = {
  REGISTER_REQUEST: "AUTH_REGISTER_REQUEST",
  REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
  REGISTER_FAILURE: "AUTH_REGISTER_FAILURE",

  LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",

  TOKEN_REQUEST: "AUTH_TOKEN_REQUEST",
  TOKEN_SUCCESS: "AUTH_TOKEN_SUCCESS",
  TOKEN_FAILURE: "AUTH_TOKEN_FAILURE",

  LOGOUT: "AUTH_LOGOUT"
};
